springbuk/odbc_adapter

lib/odbc_adapter/column.rb

Source
======
https://springbuk-glass.atlassian.net/browse/APP-2051
Problem
=======
The linked story is the first implementation of snowflake in the main Springbuk app. Springbuk is on 6.1, and ActiveRecord 6.1 is passing ** to allow kwargs through.
In our use case, there's nothing actually being passed here, but we should just keep passing them along in the call chain.
Solution
========
Adds `**kwargs` to initialize signature and pass along to super.
Testing/QA Notes
================
Tested locally in springbuk (6.1.4) and edison (6.0.3).
Post Merge Notes
================
n/a

[APP-2051] Update Column#initialize to pass on **kwargs (rails 6.1 compatibility)

---

lib/odbc_adapter/schema_statements.rb

Problem: The SchemaStatements methods get tables from all schemas without identifying which schema each came from.
Change: limit the SchemaStatements methods to return objects in the current schema only.

Limit DB info to current schema

---

lib/odbc_adapter/schema_statements.rb

The SchemaStatements modules did not support quoted database and schema names. This support is needed because of the sandbox3-st database.

[MOJ-92] Corrections for handling names

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/column.rb
lib/odbc_adapter/schema_statements.rb

With Ruby 3 the columns function started failing. The argument list to ActiveRecord::ConnectionAdapters::Column.initialize changed to remove the table name. Ruby 2.6 did not complain about the optional argument mismatch.
Also:
Identified the primary_key function was returning the column name as uppercase. Corrected that issue.
Identified the data types returned by columns were not very usable and generally resulted in string type. Created a Snowflake table with all of the snowflake data types and verified they were mapped (except object, array and geographic).

[MOJ-95] Corrections to the columns function

---

lib/active_record/connection_adapters/odbc_adapter.rb

https://springbuk-glass.atlassian.net/browse/APP-2295
error in `odbc_adapter/lib/active_record/connection_adapters/odbc_adapter.rb:200 in translate_exception`
Update method signature to match what is used in ruby 3
TBD
TBD
TBD

[APP-2295] Update signature of translate_exception for ruby 3

---

lib/odbc_adapter/schema_statements.rb

https://springbuk-glass.atlassian.net/browse/MOJ-98
Rails is not setting default values for created_at and updated_at columns.
The SchemaStatements.columns functions returns an empty string for the default value on all columns. Rails is detecting a default value for created_at and updated_at and is not setting the column. Changing the function to replace the empty string with nil corrects the problem.
A problem remains.. ODBC driver is not returning the default value for columns. We could replace the ODBC columns call with a query of information_schema.columns if there is a need for the default values.

MOJ-98 Correct column default values

---

lib/odbc_adapter/database_statements.rb

https://springbuk-glass.atlassian.net/browse/MOJ-97
We're only ever returning `String`s from `Snowflake`
Add correct type hanlding.
As there are no tests currently for `snowflake`, the best thing to test this is to load it up locally, run some queries, and check the `ruby` types of the returned results.
Corresponding PRs:
springbuk/springbuk#6041
springbuk/edison#723
springbuk/data_management#2424
After this PR lands, we'll as need to update the `Gemfile.lock` in the other PRs to point to the newest version.

[MOJ-97] Better type handling for Snowflake

---

lib/odbc_adapter/database_statements.rb

https://springbuk-glass.atlassian.net/browse/MOJ-121
Claims page was broken upon using the new odbc adapter in master
dbms_type_cast needs to return rows at the end. Also added code to raise exceptions, since currently these circumstances shouldn't be encountered and if that changes spontaneously (such as through an snowflake odbc driver update) we want to know rather than silently have nil values.
As there are no tests currently for `snowflake`, the best thing to test this is to load it up locally, run some queries, and check the `ruby` types of the returned results.
This PR will require additional PRs be merged into springbuk, edison, and data management

Claims page was broken, discovered the bug is in the ODBC Adapter.

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/quoting.rb
lib/odbc_adapter/schema_statements.rb

https://springbuk-glass.atlassian.net/browse/MOJ-137
Trying to update records using hashes or arrays (possibly other types) was throwing a can't quote error
Can't quote error is caused by active_record not knowing what types columns are
Updated infrastructure needed for models to know what types their attributes are so it will properly handle type casting automatically.
This also removes the necessity of specifying json attributes on models.
The only reason that dbms_type_cast is still useful is for when we're executing raw queries instead of using the object model.
Pushing to SB3 Springbuk & Edison. Should have working claims pages and other parts of the application that rely on edison. Can test locally by running an edison rails console locally and running
```
Feedback.create(user_id: …
```

MOJ-137 Fix can't quote errors

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/database_statements.rb
lib/odbc_adapter/quoting.rb
lib/odbc_adapter/schema_statements.rb
lib/odbc_adapter/type/array.rb

https://springbuk-glass.atlassian.net/browse/MOJ-150
https://springbuk-glass.atlassian.net/browse/MOJ-151
Snowflake doesn't support typed arrays, but having ruby understand them anyways is useful. Develop array_of_<type> classes that can be used in attribute tags on models so the model understands these are typed arrays.
Add type mapping for the remaining native types that are returned when querying snowflake table column types.
Add array_of_intgers, array_of_binaries, etc... types that can be used with attribute tagging to quickly perform useful type coercion.
Adds mapping for the remaining snowflake types, removes mapping for JSON type (as this isn't actually a type returned by snowflake ever)
I'll encourage you to pull down this commit to your local environment. Just updating the …

MOJ-150 MOJ-151 Snowflake type mapping & array_of... types for

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/concerns/insert_attribute_stripper.rb

https://springbuk-glass.atlassian.net/browse/MOJ-450
The current method of pregenerating primary keys only works where we’ve got direct access to the code, is cumbersome, and requires specialized knowledge
Implement the `prefetch_primary_key?` and `next_sequence_value` methods on the adapter so that it'll automatically handle this for us.
Minor tweaks to InsertAttributeStripper since EasyIdentified isn't effectively deprecated by this change.
Check through QA if there's anything not covered by QA wolf you'd want to see.
None
Will need PRs to springbuk, edison, and probably DM to update the adapter.

Moj 450 update with prefetch primary key

---

lib/odbc_adapter/adapters/postgresql_odbc_adapter.rb

https://springbuk-glass.atlassian.net/browse/MOJ-451
Rails migrations that use `:boolean` as a data type fail. The odbc_adapter code uses 'bool' in the generated SQL for the symbol `:boolean`. "bool" is a Postgres alias for "boolean". Snowflake does not support that alias.
"boolean" must be used instead of "bool" in the generated SQL.
Create and test a migration.
Will need PRs to springbuk, edison, and probably DM to update the adapter.

[MOJ-451] Migrations fail when using :boolean

---

lib/odbc_adapter/concerns/insert_attribute_stripper.rb
lib/odbc_adapter/type/object.rb
lib/odbc_adapter/type/variant.rb

https://springbuk-glass.atlassian.net/browse/MOJ-366
Discovered while moving the ai_question_templates table that snowflake variant & object fields don't support store_accessor.
Continued issues with records failing validation related to the InsertAttributeStripper made me realize we could just run the validation before stripping off attributes, but then disable validation when we do the actual insert.
Variant & object types now support store_accessor
InsertAttributeStripper now validates records before stripping off attributes and then disables validation during the initial save.
Check through QA if there's anything not covered by QA wolf you'd want to see.
None
Will need PRs to springbuk, edison, and probably DM to update the adapter.

MOJ-366 Two updates for added functionality

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/quoting.rb

https://springbuk-glass.atlassian.net/browse/COR-3018
Rails database migrations for Snowflake that use add_column fail. A Rails internal call used by odbc_adapter has changed. The second argument has been dropped.
Modify the calls in odbc_adpater to the function to remove the second argument.
Test with the file db/snowflake_migrate/20230202192912_add_icd_version_fields_to_master_expert_medical_opinions_table.rb inan environment that includes the Rails 7 migration.
I tested this in my local data_management environment using the migration listed above with Snowflake enabled. Using master, the Snowflake migration and reversal were successful. Switched to the Rails 7 migration branch. The Snowflake migration failed with the expected error. Updated the `Gemfile.lock` with the SHA from this …

[COR-3018] Support Rails 7

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/active_record/merge_all.rb
lib/active_record/merge_all_persistence.rb
lib/odbc_adapter.rb
lib/odbc_adapter/quoting.rb
lib/odbc_adapter/schema_statements.rb

https://springbuk-glass.atlassian.net/browse/MOJ-574
After converting the HR uploads to snowflake, processing them is extremely slow.
Needed functionality to do bulk updates in snowflake. This needs to be done via a merge statement. During implementation, I discovered that there were issues using active record models with the rails 7 changes and needed to resolve those issues. initialize_type_map was changes to work the same way it does with most adapters (using a regex string) and related functionality was also updates to generate type strings that are SQL types.
Validate that the adapter runs in QA and that the new merge_all functionality works with the HR uploads.
None
Update springbuk 574 PR when merged. Remove the specific commit reference from the gemfile and update the lockfile.

Moj 574 speedup hr uploads processing

---

lib/odbc_adapter/version.rb
odbc_adapter.gemspec

https://springbuk-glass.atlassian.net/browse/MOJ-578
There are performance issues when pulling more than 500 records from Snowflake using the existing `ruby-odbc` gem.
Created a new Springbuk specific version of the `ruby-odbc` gem named `odbc-ruby` which addresses these performance concerns.
This should be tested in QA and Sandbox 3.  Pages that access more than 500 records from Snowflake should see performance improvements.
N/A
Related PRs:
Springbuk: https://github.com/springbuk/springbuk/pull/6649
Springboot: https://github.com/springbuk/springboot/pull/155
Edison: https://github.com/springbuk/edison/pull/878

[MOJ-578] Use new springbuk odbc-ruby gem.

---

lib/odbc_adapter/schema_statements.rb

https://springbuk-glass.atlassian.net/browse/MOJ-540
While retrieving the plan_years controller I ran into issues as a result of the obdc adapter not retrieving default values
Spent a lot of time reviewing the odbc_ruby library to get a good understanding of why we aren't getting default values. In the end, I wasn't able to see anything being done wrong. I don't have a method of testing the snowflake odbc driver itself to confirm, but my only reasonable solution is that this is an issue with the snowflake driver. If it's not going to return type information, that information can also easily be gotten by querying the information schema so I converted the odbc adapter function that retrieve column data to query the information schema.
General browsing of qa and attempting to do updates …

Moj 519 plan years controller

---

lib/active_record/merge_all.rb

https://springbuk-glass.atlassian.net/browse/APP-3029
Issue was reported where HR uploads weren't properly updating biometics.
Taking a look at the cause, it turns out the code that I added to remove duplicate entries was too aggressive. It was recognizing nil primary keys, which were used to indicate a new records to be inserted, as all being the same record ID so it would prune all but the last record to be inserted.
All records with a nil primary key get their primary key replaced by a new object, which will never compare true to anything else.
Attempt to use the merge_all functionality with a mixture of new and update records to confirm that both work.
ODBC adapter changes are also deployed to APP QA
Create PR to merge updated ODBC adapter into springbuk gemfile

APP-3029 Fixes prune duplicates.

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/adapters/postgresql_odbc_adapter.rb
lib/odbc_adapter/column.rb
lib/odbc_adapter/database_statements.rb
lib/odbc_adapter/quoting.rb
lib/odbc_adapter/schema_statements.rb
lib/odbc_adapter/type/variant.rb
odbc_adapter.gemspec

Updates the adapter to handle Rails version 7.1.2
**lib/active_record/connection_adapters/odbc_adapter.rb**
ActiveRecord was not correctly assigning the instance variable. Manually assigning it here.
**lib/odbc_adapter/database_statements.rb**
This method was being called by active record, but did not exist in this adapter, adding it to copy functionality from other adapters
**lib/odbc_adapter/quoting.rb**
This method was moved
**odbc_adapter.gemspec**
Upgrading to use new version of ActiveRecord

Update adapter to handle rails 7

---

lib/odbc_adapter/concerns/easy_identified.rb

Update done for the springbuk Rails 7 update.
Update to use self.id instead of self[:id] as the later has been deprecated

APP-3014 Rails 7 update

---

lib/active_record/connection_adapters/odbc_adapter.rb

If a return value should be provided after insert we need to call `auto_populated?` (the same method used in the default Column implementation) when dealing with a Column object that isn't the ODBC Adapter's version.
This can occur when a model is initialized using Postgres but then that model is needed to write into Snowflake.
When a model is initialized from Postgres the Column objects that are created are all an instance of **PostgreSQL::Column**. When they are initialized from Snowflake they are an **ODBCAdapter::Column**.
The Active Record Abstract Adapter (activerecord/lib/active_record/connection_adapters/abstract_adapter.rb) defines the `return_value_after_insert?` as:
```
def return_value_after_insert?(column) # :nodoc:
column.auto_populated?
end
```
and the default …

[APP-3305] Use auto_populated? for Column models initialized from Postgres

---

lib/odbc_adapter/schema_statements.rb

As part of the work for supporting syncing of activations from production to non-production environments we need to pull the category and minor category tables. The production version of these tables will be accessible as views in the non-production environments and the service needs to be able to determine if the views exist.
This PR adds a proper implementation of `views`, initializing the available views from Snowflake and allowing the `view_exists?` method to actually work on the odbc adapter

[APP-3470] Initialize known views to support checking for existence

---

lib/odbc_adapter/schema_statements.rb

Guard against missing schema when querying for the views.
There was an issue running the CI tests for Springbuk after using the new adapter created in [PR](https://github.com/springbuk/odbc_adapter/pull/37). It appears that the schema may not exist in CI at the time a query for the views is performed. This change will protect against that.
I made a change to my branch of Springbuk to use the specific commit with the odbc adapter changes that guard against the missing schema (ref: "9d354792df6264468719ac510fdcbdab5544d34b") and it finally passed the CI tests

[APP-3470] protect against missing schema

---

.rubocop.yml
lib/active_record/connection_adapters/odbc_adapter.rb
lib/aws_secrets_manager.rb
lib/odbc_adapter/connect_common.rb
lib/odbc_adapter/version.rb
odbc_adapter.gemspec

This version of the ODBC adapter adds a new feature that allows it to attempt to repair invalid credentials when a PEM file is used to connect to Snowflake.
Snowflake connections support using a PEM file through the use of two connection attributes: PRIV_KEY_FILE & PRIV_KEY_FILE_PWD. These values have typically been used in local development environments where each developer has their own unique set of connection credentials. With this new release the connection string may specify an AWS secret key id as the value of PRIV_KEY_FILE instead of a filepath to the PEM file.
For example, in development environments the following values are typically used:
```
PRIV_KEY_FILE=<%= Rails.root.join(ENV['SF_KEY_FILE'].to_s) %>
PRIV_KEY_FILE_PWD=<%= ENV['SF_KEY_FILE_PWD'].to_s %>
```
With this new …

[APP-3659] Add Support for Fetching Credentials from AWS

---

lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter/database_statements.rb

https://springbuk-glass.atlassian.net/browse/APP-3728
We're running into an error on Edison that reads
```
08001 (390114) Authentication token has expired.  The user must authenticate again.
```
Modifying the ODBC internals to automatically reconnect when this error case happens should solve this.
This change was a doozy of trial/error that led to the discovery that the `translate_exception` method is no longer (perhaps after the move from rails 6 -> 7) being called as intended.  As such, I've removed the `translate_exception` override code,  moved the error based reconnect functionality from there to the `internal_exec_query` method, and included the new error cases.  I also added functionality to rerun the failing SQL in these cases.
I've deployed this change across the various SB4 …

[APP-3728] Attempt re auth when token expires

---

.idea/.gitignore
.idea/misc.xml
.idea/modules.xml
.idea/odbc_adapter.iml
.idea/vcs.xml
lib/active_record/connection_adapters/odbc_adapter.rb
lib/odbc_adapter.rb
lib/odbc_adapter/adapters/snowflake/database_metadata.rb
lib/odbc_adapter/adapters/snowflake/schema_statements.rb
lib/odbc_adapter/adapters/snowflake_odbc_adapter.rb
lib/odbc_adapter/connect_common.rb
lib/odbc_adapter/database_metadata.rb
lib/odbc_adapter/database_statements.rb
lib/odbc_adapter/quoting.rb
lib/odbc_adapter/schema_statements.rb

https://springbuk-glass.atlassian.net/browse/APP-4370
Rails needs upgraded. The version we were on leaves support at the end of the month.
Rails apparently is unconcerned about large breaking adapter changes on minor rails version upgrades.
Differences accounted for going from rails 7.1 to 7.2:
- The entire way in which adapters are instantiated was changed around.
- There used to be an API requirement that said "If your adapter is named "MyAdapter" it had to pathch ActiveRecord::Base with a class/singleton method named "my_adapter_connection" that would instantiate the adapter. This is gone and adapters are now instantiated directly. Adapters are also expected to register themselves, since there's not a method for instantiating them on ActiveRecord::Base.
- As a result of direct adapter …

App 4370 upgrade rails
